#!/bin/bash
#PBS -N wer_base
#PBS -l select=1:ngpus=1:ncpus=8:mem=32gb
#PBS -l walltime=3:00:00
#PBS -P personal-REDACTED_NSCC_USER
#PBS -o logs/base.log
#PBS -e logs/base.err
#PBS -j oe

module load cuda/12.2.1
export LD_LIBRARY_PATH=/app/libs/cudnn/12-8.9.4.25/lib:$LD_LIBRARY_PATH

source /app/apps/miniforge3/25.3.1/etc/profile.d/conda.sh
conda activate whisper

export HF_DATASETS_CACHE=/scratch/users/ntu/REDACTED_NSCC_USER/hf_cache
export WHISPER_CACHE=/scratch/users/ntu/REDACTED_NSCC_USER/whisper_cache
mkdir -p $HF_DATASETS_CACHE $WHISPER_CACHE

cd /scratch/users/ntu/REDACTED_NSCC_USER/indian-asr-bench

python task1_whisper_base/wer_whisper_base.py
