#!/bin/bash
#PBS -N wer_medium
#PBS -l select=1:ngpus=1:ncpus=8:mem=48gb
#PBS -l walltime=4:00:00
#PBS -P personal-REDACTED_NSCC_USER
#PBS -o logs/medium.log
#PBS -e logs/medium.err
#PBS -j oe

module load cuda/12.2.1
export LD_LIBRARY_PATH=/app/libs/cudnn/12-8.9.4.25/lib:$LD_LIBRARY_PATH

source /app/apps/miniforge3/25.3.1/etc/profile.d/conda.sh
conda activate /scratch/users/ntu/REDACTED_NSCC_USER/envs/whisper

export HF_DATASETS_CACHE=/scratch/users/ntu/REDACTED_NSCC_USER/hf_cache
export WHISPER_CACHE=/scratch/users/ntu/REDACTED_NSCC_USER/whisper_cache
mkdir -p $HF_DATASETS_CACHE $WHISPER_CACHE

cd /scratch/users/ntu/REDACTED_NSCC_USER/indian-asr-bench

python task2_whisper_medium/wer_whisper_medium.py
