#!/bin/bash
#PBS -N qwen3_asr
#PBS -l select=1:ngpus=1:ncpus=8:mem=32gb
#PBS -l walltime=6:00:00
#PBS -P personal-REDACTED_NSCC_USER
#PBS -o logs/qwen3.log
#PBS -e logs/qwen3.err
#PBS -j oe

module load cuda/12.2.1
export LD_LIBRARY_PATH=/app/libs/cudnn/12-8.9.4.25/lib:$LD_LIBRARY_PATH

source /app/apps/miniforge3/25.3.1/etc/profile.d/conda.sh
conda activate /scratch/users/ntu/REDACTED_NSCC_USER/envs/qwen3_env

export HF_DATASETS_CACHE=/scratch/users/ntu/REDACTED_NSCC_USER/hf_cache
export HF_HOME=/scratch/users/ntu/REDACTED_NSCC_USER/hf_cache
mkdir -p $HF_DATASETS_CACHE logs

cd /scratch/users/ntu/REDACTED_NSCC_USER/indian-asr-bench

python task5_qwen3_asr/wer_qwen3.py
